import { Navigation } from "./navigation.model";

export const navigation: Navigation[] = [
  {
    id: "DASHBOARD",
    title: "DASHBOARD",
    translate: "SIDEBAR.DASHBOARD",
    type: "group",
    icon: "Design/Layers",

    children: [
      {
        id: "MAIN_DASHBOARD",
        title: "MAIN_DASHBOARD",
        translate: "SIDEBAR.MAIN_DASHBOARD",
        type: "item",
        icon: "Shopping/Settings",
        url: "/dashboard",
      },
      {
        id: "POSITION_GIS",
        title: "POSITION_GIS",
        translate: "SIDEBAR.POSITION_GIS",
        type: "item",
        icon: "Map/Marker2",
        url: "https://geosmart.dmt.gov.ae/ADCMC",
      },
    ],
  },

  {
    id: "EVENTSMODULES",
    title: "EVENTSMODULES",
    translate: "SIDEBAR.EVENTSMODULES",
    type: "group",
    icon: "Code/Warning-2",
    children: [
      {
        id: "EVENT_LOG",
        title: "EVENT_LOG",
        translate: "EVENTSMODULES.EVENT_LOG",
        type: "item",
        icon: "Design/Circle",
        url: "/events-log",
      },
      {
        id: "PUBLIC_ANNOUNCEMENT",
        title: "PUBLIC_ANNOUNCEMENT",
        translate: "EVENTSMODULES.PUBLIC_ANNOUNCEMENT",
        type: "item",
        icon: "Design/Circle",
        url: "incidents/incidents/all",
      },
      {
        id: "HOT_ANNOUNCEMENT",
        title: "HOT_ANNOUNCEMENT",
        translate: "EVENTSMODULES.HOT_ANNOUNCEMENT",
        type: "item",
        icon: "Design/Circle",
        url: "incidents/incidents/important",
      },
      {
        id: "CLOSED_ANNOUNCEMENT",
        title: "CLOSED_ANNOUNCEMENT",
        translate: "EVENTSMODULES.CLOSED_ANNOUNCEMENT",
        type: "item",
        icon: "Design/Circle",
        url: "incidents/incidents/closed",
      },
      {
        id: "CALL",
        title: "CALL",
        translate: "SIDEBAR.CALL",
        type: "item",
        icon: "Design/Circle",
        url: "/call-duty",
      },
      // {
      //   id: "INCIDENTSSCHEDULAR",
      //   title: "INCIDENTSSCHEDULAR",
      //   translate: "SIDEBAR.INCIDENTSSCHEDULAR",
      //   type: "item",
      //   icon: "Design/Circle",
      //   url: "incidents",
      // },
    ],
  },

  {
    id: "TASKS",
    title: "TASKS",
    translate: "SIDEBAR.TASKS",
    type: "item",
    icon: "Home/Timer",
    url: "/incidents/tasks/incoming",
  },
  // {
  //   id: "TRENDING",
  //   title: "TRENDING",
  //   translate: "SIDEBAR.TRENDING",
  //   type: "item",
  //   icon: "Home/Timer",
  //   url: "/trending/dashboard",
  // },
  {
    id: "CORRERSPONDENCE",
    title: "CORRERSPONDENCE",
    translate: "SIDEBAR.CORRERSPONDENCE",
    type: "group",
    icon: "Communication/Mail-opened",
    children: [
      {
        id: "CORRERSPONDENCE",
        title: "CORRERSPONDENCE",
        translate: "SIDEBAR.CORRERSPONDENCE",
        type: "item",
        icon: "Communication/Mail-opened",
        url: "/correspondences-management/correspondences",
      },

      {
        id: "CIRCULARS",
        title: "CIRCULARS",
        translate: "SIDEBAR.CIRCULARS",
        type: "item",
        icon: "Devices/LTE2",
        url: "/circulars-management",
      },
    ],
  },

  {
    id: "REPORTS",
    title: "REPORTS",
    translate: "SIDEBAR.REPORTS",
    type: "group",
    icon: "Files/Selected-file",
    url: "/reports-management",
    children: [
      {
        id: "GENERALPOSITION",
        title: "GENERALPOSITION",
        translate: "INCIDENTS.GENERALPOSITION",
        type: "item",
        icon: "Design/Circle",
        url: "incidents/view/112",
      },
      {
        id: "GENERALPOSITION",
        title: "GENERALPOSITION",
        translate: "INCIDENTS.PRIVATEPOSITION",
        type: "item",
        icon: "Design/Circle",
        url: "incidents/private-position/112",
      },
      {
        id: "DAILY_BREVITY",
        title: "DAILY_BREVITY",
        translate: "DAILY_BREVITY.HEADER",
        type: "item",
        icon: "Design/Circle",
        url: "daily-management",
      },

      {
        id: "MAIL_REPORT",
        title: "MAIL_REPORT",
        translate: "REPORTS.MAIL_REPORT",
        type: "item",
        icon: "Design/Circle",
        url: "MAIL_REPORT",
      },

      {
        id: "GENERAL_REPORT",
        title: "GENERAL_REPORT",
        translate: "REPORTS.GENERAL_REPORT",
        type: "item",
        icon: "Design/Circle",
        url: "GENERAL_REPORT",
      },
      {
        id: "RESOURCES_REPORT",
        title: "RESOURCES_REPORT",
        translate: "REPORTS.RESOURCES_REPORT",
        type: "item",
        icon: "Design/Circle",
        url: "RESOURCES_REPORT",
      },
      // {
      //   id: "SMS_REPORT",
      //   title: "SMS_REPORT",
      //   translate: "REPORTS.RESOURCES_REPORT",
      //   type: "item",
      //   icon: "Design/Circle",
      //   url: "RESOURCES_REPORT",
      // },
    ],
  },

  {
    id: "USERMANAGEMENT",
    title: "USERMANAGEMENT",
    translate: "SIDEBAR.USERMANAGEMENT",
    type: "group",
    icon: "Communication/Group",
    children: [
      {
        id: "ORGANIZATIONS",
        title: "ORGANIZATIONS",
        translate: "ORGANIZATIONS.ORGANIZATIONS",
        type: "item",
        icon: "Communication/Shield-user",
        url: "/organizations",
      },
      {
        id: "GROUPSMODULES",
        title: "GROUPSMODULES",
        translate: "SIDEBAR.GROUPSMODULES",
        type: "item",
        icon: "Communication/Group",
        url: "/groups-management/groups",
      },
      {
        id: "USERS",
        title: "USERS",
        translate: "SIDEBAR.USERS",
        type: "item",
        icon: "Communication/Shield-user",
        url: "/user-management/users",
      },
      {
        id: "ROLES",
        title: "ROLES",
        translate: "SIDEBAR.ROLES",
        type: "item",
        icon: "Code/Lock-overturning",
        url: "/user-management/roles",
      },
      {
        id: "EVENTSMODULES",
        title: "EVENTSMODULES",
        translate: "SIDEBAR.EVENTSMODULES",
        type: "item",
        icon: "Code/Warning-2",
        url: "/events-management",
      },
    ],
  },

  {
    id: "DATACALL",
    title: "DATACALL",
    translate: "SIDEBAR.DATACALL",
    type: "group",
    icon: "Layout/Layout-left-panel-2",
    children: [
      {
        id: "COMPANY_PROFILE",
        title: "COMPANY_PROFILE",
        translate: "INCIDENTS.COMPANY_PROFILE",
        type: "item",
        icon: "/Home/Building",
        url: "/company-profile",
      },
      {
        id: "PERSONAL_INFO",
        title: "PERSONAL_INFO",
        translate: "PERSONAL_INQUIRY.PERSONAL_INFO",
        type: "item",
        icon: "Communication/Shield-user",
        url: "/personal-inquiry",
      },
       {
        id: "DOH_INFO",
        title: "DOH_INFO",
        translate: "DOH_DASHBOARD.DOH_DASHBOARD",
        type: "item",
        icon: "Devices/Display1",
        url: "/doh-dashboard",
      },
    ],
  },

  {
    id: "HOT_LINKES",
    title: "HOT_LINKES",
    translate: "EVENTSMODULES.HOT_LINKES",
    type: "group",
    icon: "Layout/Layout-grid",
    children: [
      {
        id: "MAKE_SUGGESTIONS",
        title: "MAKE_SUGGESTIONS",
        translate: "SIDEBAR.SUGGESTIONS.MAKE",
        type: "item",
        icon: "Devices/Display1",
        url: "/suggestions/make",
      },
      {
        id: "MANAGE_SUGGESTIONS",
        title: "MANAGE_SUGGESTIONS",
        translate: "SIDEBAR.SUGGESTIONS.MANAGE",
        type: "item",
        icon: "Devices/Display1",
        url: "/suggestions/manage",
      },
      {
        id: "LIBRARY",
        title: "LIBRARY",
        translate: "SIDEBAR.LIBRARY",
        type: "item",
        icon: "Home/Library",
        url: "/libraries-management",
      },
      {
        id: "CONTINUITY",
        title: "CONTINUITY",
        translate: "SIDEBAR.CONTINUITY",
        type: "item",
        icon: "Shopping/Chart-line1",
        url: "/under-build",
      },
      {
        id: "TRAININGANDEXERCISE",
        title: "TRAININGANDEXERCISE",
        translate: "SIDEBAR.TRAININGANDEXERCISE",
        type: "item",
        icon: "Home/Stairs",
        url: "/under-build",
      },

      {
        id: "SHIFT",
        title: "SHIFT",
        translate: "SIDEBAR.SHIFT",
        type: "item",
        icon: "Code/Git4",
        url: "/under-build",
      },
      {
        id: "NEWS",
        title: "NEWS",
        translate: "SIDEBAR.NEWS",
        type: "item",
        icon: "Media/News",
        url: "/news",
      },
      {
        id: "RESOURCE",
        title: "RESOURCE",
        translate: "SIDEBAR.RESOURCE",
        type: "item",
        icon: "Shopping/Box2",
        url: "/resources-management",
      },
      {
        id: "LOGIN_ATTEMPT",
        title: "LOGIN_ATTEMPT",
        translate: "SIDEBAR.LOGIN_ATTEMPT",
        type: "item",
        icon: "Code/Lock-overturning",
        url: "/login-attempts",
      }
    ],
  },
];

export const quickNavigation: Navigation[] = [
  {
    id: "SYS_STATUS",
    title: "SYS_STATUS",
    translate: "SYS_STATUS.TITLE",
    type: "item",
    icon: "Code/Warning-2",
    // url: "",
    privilege: "PRIV_ED_SYS_THM",
  },
  {
    id: "INCIDENTS",
    title: "INCIDENTS",
    translate: "INCIDENTS.NEW_INCIDENTS",
    type: "item",
    icon: "Communication/Urgent-mail",
    url: "/incidents/report",
    privilege: "PRIV_CR_INC",
  },
  {
    id: "TASKS",
    title: "TASKS",
    translate: "DASHBOARD.NEW_TASK",
    type: "item",
    icon: "Devices/LTE2",
    url: "/incidents/createTask",
    privilege: "PRIV_CR_TASK",
  },
  {
    id: "CORRERSPONDENCE",
    title: "CORRERSPONDENCE",
    translate: "CORRERSPONDENCE.ADD",
    type: "item",
    icon: "Communication/Mail-opened",
    url: "/correspondences-management/correspondences/add",
    privilege: "PRIV_CR_CORR",
  },
  {
    id: "RESOURCE",
    title: "RESOURCE",
    translate: "RESOURCE.CREATE_RESOURCE",
    type: "item",
    icon: "Shopping/Box2",
    url: "/resources-management/resources/add",
    privilege: "PRV_CR_ASST",
  },
];
