version: "3.4"
services:
  slamah-fe:
    restart: always
    image: #{IMG_NAME}#:#{TAG}#
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      Sddappsd: 10.24.10.55
    ports:
      - "4200:80"
