export const environment = {
  NAME: 'STG',
  production: true,
  appVersion: 'v712demo1',
  USERDATA_KEY: 'authf649fc9a5f55',
  isMockEnabled: true,
  apiUrl: 'ecms/v1',
  apiUrlNoV1: 'ecms',
  apiUrlV2: 'ecms/v2',
  SOCKET_ENDPOINT: 'ecms/ecms-websocket',
  UAE_PASS_HOST: 'https://qa-id.uaepass.ae',
  UAE_PASS_CLIENT_ID: 'adcmcm_web_stage',
  UAE_PASS_ROUTE: '',
  ADMGIS_ROOT_ROUTE: '/admgis',
  firebase: {
    apiKey: 'AIzaSyAmgMp_-dV4bkIsixLzSwF23JSfF3pc0Tk',
    authDomain: 'ecms-staging.firebaseapp.com',
    projectId: 'ecms-staging',
    storageBucket: 'ecms-staging.appspot.com',
    messagingSenderId: '300863038478',
    appId: '1:300863038478:web:5867b4ed70d197b7b8c85f',
    measurementId: 'G-PW9FSS9HPG',
    vapidKey:
      'BMfuLHUqKCYjsPieQyuDOFGRgVFXd_H-WUA9jhyYmw0uBc1zgVPCZ9cOYDth7rlPm3W_hpjLFfOlG6LVMA5ho9I',
  },
};
