export const commonDataItem = [
  {
    key: 'correspondenceStatus',
    icon: 'Communication/Group-chat',
    type: 'commonPublic',
    hidden: true,
    endPoint: 'correspondence-statuses',
  },
  {
    key: 'dailySumariesReportOptType',
    icon: 'Files/Selected-file',
    type: 'commonPublic',
    hidden: true,
    endPoint: 'dailysummary-type',
  },

  {
    key: 'incidentStatus',
    icon: 'Code/Info-circle',
    type: 'commonPublic',
    hidden: true,
    endPoint: 'incident-statuses',
  },

  {
    key: 'reasons',
    icon: 'Code/Question-circle',
    type: 'commonPublic',
    hidden: true,
    endPoint: 'reasons',
  },
  {
    key: 'priorities',
    icon: 'Text/Align-left',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'priorities',
  },
  {
    key: 'reportingVias',
    icon: 'Communication/Mail-opened',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'reporting-via',
  },
  {
    key: 'cities',
    icon: 'Map/Marker2',
    type: 'commonPublic',
    hidden: true,
    endPoint: 'cities',
  },
  {
    key: 'confidentialties',
    icon: 'Code/Lock-circle',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'circular-confidentialties',
  },
  {
    key: 'libraryCategories',
    icon: 'Home/Library',
    type: 'commonPublic',
    hidden: true,
    endPoint: 'library/categories',
  },
  {
    key: 'assetsCategory',
    icon: 'Shopping/Box3',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'assets-category',
  },
  {
    key: 'alertnessLevel',
    icon: 'Media/Equalizer',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'alertness-level',
  },
  {
    key: 'assetsGroup',
    icon: 'Shopping/Box3',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'assets-group',
  },

  {
    key: 'dailySummaryReportStatus',
    icon: 'Code/Time-schedule',
    type: 'commonPublic',
    hidden: true,
    endPoint: '',
  },
  {
    key: 'circularStatus',
    icon: 'Devices/LTE2',
    type: 'commonPublic',
    hidden: true,
    endPoint: '',
  },
  {
    key: 'newsTypes',
    icon: 'Home/Earth',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'news-type',
  },
  {
    key: 'hospitals',
    icon: 'Home/Building',
    type: 'commonPublic',
    hidden: false,
    endPoint: 'hospitals',
  },
  {
    key: 'incidentCategories',
    icon: 'Electric/Highvoltage',
    type: '',
    customTemplate: true,
    hidden: false,
    endPoint: 'incident-categories',
  },

  {
    key: 'localRisks',
    icon: 'Electric/Highvoltage',
    type: '',
    customTemplate: true,
    hidden: true,
    endPoint: 'local-risk',
  },
  {
    key: 'kpi',
    icon: 'Layout/Layout-top-panel-2',
    type: 'commonPublic',
    customTemplate: true,
    hidden: true,
    endPoint: '',
  },
  {
    key: 'kpi-v2',
    icon: 'Layout/Layout-top-panel-2',
    type: '',
    customTemplate: true,
    hidden: false,
    endPoint: '',
  },
  {
    key: 'emergencyLevels',
    icon: 'Shopping/Chart-line1',
    type: 'commonPrivate',
    hidden: true,
    endPoint: 'emergency-levels',
  },

  {
    key: 'HEADER_MENU',
    icon: 'Layout/Layout-top-panel-1',
    type: '',
    hidden: true,
    endPoint: '',
  },
  {
    key: 'NOTIFICATION_MANAGEMENT',
    icon: 'General/Notifications1',
    type: '',
    hidden: true,
    endPoint: '',
  },
  {
    key: 'RANKS',
    icon: 'Media/DVD',
    type: '',
    hidden: true,
    endPoint: '',
  },
  {
    key: 'MOBILE_VERSIONS',
    icon: 'Devices/Android',
    type: '',
    customTemplate: true,
    hidden: true,
    endPoint: 'mobile-versions',
  },
  {
    key: 'NOTIFICATIONS',
    icon: 'General/Notifications1',
    type: '',
    customTemplate: true,
    hidden: true,
    endPoint: 'mobile-versions',
  },
];
