/* tslint:disable */
/* eslint-disable */
import { AddressesType } from './addresses-type';
import { DetailType } from './detail-type';
import { IdentityCardType } from './identity-card-type';
import { ImmigrationFileType } from './immigration-file-type';
import { PassportType } from './passport-type';
import { PersonNameType } from './person-name-type';
import { PersonProfileWivesType } from './person-profile-wives-type';
import { QualificationType } from './qualification-type';
import { RelativesType } from './relatives-type';
import { SponsorType } from './sponsor-type';
export interface PersonProfileType {
  addresses?: AddressesType;
  birthCertificateNo?: string;
  birthCity?: DetailType;
  birthCountry?: DetailType;
  birthDate?: string;
  birthEmirate?: DetailType;
  birthPlaceArabic?: string;
  birthPlaceEnglish?: string;
  bloodType?: string;
  cardSerialNo?: string;
  companyAr?: string;
  companyCode?: number;
  companyEn?: string;
  companyTypeCode?: number;
  disability?: number;
  edbarahNo?: string;
  faith?: DetailType;
  familyBookNo?: string;
  familyBookRelation?: number;
  familyBookStartDate?: string;
  familyCount?: number;
  familyFemaleCount?: number;
  familyMaleCount?: number;
  freeEducation?: number;
  freeHealth?: number;
  gender?: DetailType;
  identityCard?: IdentityCardType;
  immigrationFile?: ImmigrationFileType;
  isBlackListed?: boolean;
  isInsideCountry?: boolean;
  khulasitQaidNo?: string;
  maritalStatus?: DetailType;
  motherFirstNameArabic?: string;
  motherFirstNameEnglish?: string;
  motherNameArabic?: string;
  motherNameEnglish?: string;
  nationality?: DetailType;
  occupation?: DetailType;
  passport?: PassportType;
  personClassification?: number;
  personName?: PersonNameType;
  personType?: DetailType;
  pimarylangCode?: number;
  portrait?: Array<string>;
  prPortrait?: Array<string>;
  previousNationality?: DetailType;
  qualification?: QualificationType;
  relatives?: RelativesType;
  religion?: DetailType;
  signature?: Array<string>;
  socialSupportStatus?: number;
  sponsor?: SponsorType;
  title?: DetailType;
  un?: string;
  wives?: PersonProfileWivesType;
}

