export enum AppCacheKeys {
  LANG = 'lang',
  USER_PRIVILEGES = 'userPrivileges',
  LANGUAGE = 'language',
  FIRST_LOGIN = 'firstLogin',
  THEME = 'theme',
  TOKEN = 'token',
  COMMON_DATA = 'commonData',
  ORG = 'org',
  UAE_PASS_ERROR = 'UaePassError',
  UAE_PASS_ERR_CODE = 'UaePassErroCode',
  LOGIN_TYPE = 'LOGIN_TYPE',
  UAE_PASS_ORG = 'uae-pass-org',
  ORGS = 'ORGS',
  MODULE_PRIVILEGES = 'MODULE_PRIVILEGES',
  USER_FIREBASE_TOKEN = 'USER_FIREBASE_TOKEN',
  SESSION = 'session',
}
