export enum UploadTagIdConst {
  // old values
  INCIDENT = 1,
  WORK_LOG = 2,
  TASK = 6,
  TASK_WORK_LOG = 4,

  //  xlxs  values
  DOC = 3,
  TASKS = 4,//5
  PASSPORT = 7,
  CORRESPONDENCE_PHOTO = 8,
  CIRCULAR = 9,
  CORRESPONDENCE_CIRCULAR = 10,
  BASE_LIBRARY_CIRCULAR = 11,
  OP_REPORT = 12,
  LIBRARY_OP_REPORT = 13,
  CORR_ATTACHMENT_0 = 14,
  CORR_ATTACHMENT_1 = 15,
  CORR_ATTACHMENT_2 = 16,
  CORR_ATTACHMENT_3 = 17,
  SIGNATURE = 18,
  USER_PHOTO = 19,
  ATT = 20,
  INCIDENT_TEST = 21,
  LOGOHORIZENTAL = 22,
  REPORT = 23,
  MAIL = 25,
  ADCDA_DAILY_REPORT = 26,
  ADCDA_AVAILABILITY_REPORT = 27,
  INTERIM_INCIDENT = 28,
  ASSETS_IMAGE = 29,
  REPORTER_IMAGE = 31,
  PLAN_SITUATION = 32,
  SHIFT_SITUATION = 33,
  BC_ACTIVITYANALYSIS_WORKLOG = 34
}
